
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class Simboloss {
  /* terminals */
  public static final int parc = 20;
  public static final int para = 19;
  public static final int _bool = 24;
  public static final int _if = 27;
  public static final int _retorno = 26;
  public static final int coma = 16;
  public static final int _void = 25;
  public static final int _int = 21;
  public static final int numero = 4;
  public static final int por = 8;
  public static final int _double = 22;
  public static final int or = 11;
  public static final int _else = 28;
  public static final int _string = 23;
  public static final int ID = 2;
  public static final int llavc = 18;
  public static final int llava = 17;
  public static final int menos = 7;
  public static final int menor = 13;
  public static final int div = 9;
  public static final int igual = 5;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int punc = 15;
  public static final int IDS = 3;
  public static final int mas = 6;
  public static final int igualigual = 12;
  public static final int and = 10;
  public static final int mayor = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "IDS",
  "numero",
  "igual",
  "mas",
  "menos",
  "por",
  "div",
  "and",
  "or",
  "igualigual",
  "menor",
  "mayor",
  "punc",
  "coma",
  "llava",
  "llavc",
  "para",
  "parc",
  "_int",
  "_double",
  "_string",
  "_bool",
  "_void",
  "_retorno",
  "_if",
  "_else"
  };
}

